# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12s1tisaCB9p_XIwnWjZkkd8Sy8VSlZJA
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Handwashing Case Study Dashboard",
    layout="wide",
)

# ---------------- TITLE & INTRO ----------------
st.title("🧼 Handwashing Case Study Dashboard")

st.markdown(
    """
This dashboard explores historical data on births and deaths in two clinics,
highlighting how the introduction of **handwashing** affected mortality rates.

Upload the dataset, choose a clinic and time range, and explore the trends.
"""
)

# ---------------- SIDEBAR: FILE UPLOAD ----------------
st.sidebar.header("📁 Data Input")
file = st.sidebar.file_uploader(
    "Upload the `yearly_deaths_by_clinic.csv` file",
    type="csv"
)

if file is not None:
    # --------------- LOAD DATA ----------------
    df = pd.read_csv(file)

    # Column names from your file
    year_col = "Year"
    births_col = "Birth"
    deaths_col = "Deaths"
    clinic_col = "Clinic"

    # Calculate mortality rate
    df["Mortality Rate"] = df[deaths_col] / df[births_col]

    # --------------- SIDEBAR FILTERS ----------------
    st.sidebar.header("🔍 Filters")

    # Filter by clinic
    clinics = sorted(df[clinic_col].unique())
    selected_clinic = st.sidebar.selectbox("Select a clinic", clinics)
    df_filtered = df[df[clinic_col] == selected_clinic].copy()

    # Filter by year range
    years = sorted(df_filtered[year_col].unique())
    year_min, year_max = int(min(years)), int(max(years))

    year_range = st.sidebar.slider(
        "Select Year Range",
        min_value=year_min,
        max_value=year_max,
        value=(year_min, year_max),
        step=1
    )

    df_filtered = df_filtered[
        (df_filtered[year_col] >= year_range[0]) &
        (df_filtered[year_col] <= year_range[1])
    ]

    # --------------- MAIN LAYOUT (TABS) ----------------
    tab1, tab2, tab3, tab4 = st.tabs(
        ["📋 Data", "📈 Trends", "📊 Births vs Deaths", "📝 Findings"]
    )

    # ---- TAB 1: DATA PREVIEW ----
    with tab1:
        st.subheader("Raw Data Preview")
        st.dataframe(df_filtered, use_container_width=True)

    # ---- TAB 2: TRENDS (DEATHS & MORTALITY) ----
    with tab2:
        st.subheader(f"Trends in {selected_clinic}")
        col1, col2 = st.columns(2)

        # Line Chart: Deaths Over Time
        with col1:
            st.markdown("**Deaths Over Time**")
            fig, ax = plt.subplots()
            ax.plot(df_filtered[year_col], df_filtered[deaths_col], marker="o")
            ax.set_xlabel("Year")
            ax.set_ylabel("Deaths")
            ax.set_title("Deaths per Year")
            st.pyplot(fig)

        # Line Chart: Mortality Rate Over Time
        with col2:
            st.markdown("**Mortality Rate Over Time (Deaths / Births)**")
            fig2, ax2 = plt.subplots()
            ax2.plot(df_filtered[year_col], df_filtered["Mortality Rate"], marker="o")
            ax2.set_xlabel("Year")
            ax2.set_ylabel("Mortality Rate")
            ax2.set_title("Mortality Rate per Year")
            st.pyplot(fig2)

    # ---- TAB 3: BIRTHS VS DEATHS ----
    with tab3:
        st.subheader(f"Births vs Deaths in {selected_clinic}")

        st.markdown(
            "This chart compares the total number of births and deaths per year "
            "to show how the absolute counts changed over time."
        )

        fig3, ax3 = plt.subplots()
        ax3.bar(
            df_filtered[year_col],
            df_filtered[births_col],
            label="Births",
            alpha=0.6,
        )
        ax3.bar(
            df_filtered[year_col],
            df_filtered[deaths_col],
            label="Deaths",
            alpha=0.8,
        )
        ax3.set_xlabel("Year")
        ax3.set_ylabel("Count")
        ax3.legend()
        st.pyplot(fig3)

    # ---- TAB 4: FINDINGS ----
    with tab4:
        st.subheader("Summary of Findings")

        st.write(
            "Across the selected years and clinic, deaths tend to decline after "
            "handwashing is introduced. Even as many births continued to occur, "
            "the number of deaths and the mortality rate dropped, indicating a "
            "substantial reduction in maternal mortality."
        )

        st.write(
            "These trends support the conclusion that systematic handwashing and "
            "improved hygiene practices played a key role in saving lives and "
            "reducing childbed fever among mothers."
        )

else:
    st.info("👈 Upload your `yearly_deaths_by_clinic.csv` file in the sidebar to begin.")